config/routes.rb
Rails.application.routes.draw do
  resources :taggings
  # resources :tags
  resources :media
  resources :collaborators
  resources :instructors
  resources :projects

  root 'projects#index'
  get 'tags/:tag', to: 'projects#index', as: :tag
  get 'login', to: 'projects#login'
  get 'contact', to: 'projects#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :collaborators, inverse_of: :project, dependent: :destroy
    has_many :instructors, inverse_of: :project, dependent: :destroy
    has_many :media,->{ order( :order)}, inverse_of: :project, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings, dependent: :destroy

    accepts_nested_attributes_for :collaborators, allow_destroy: true
    accepts_nested_attributes_for :instructors, allow_destroy: true
    accepts_nested_attributes_for :media, allow_destroy: true

    def self.tagged_with(name)
        Tag.find_by!(name: name).projects
    end
    
    # def self.tag_counts
    #     Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    # end
    def self.tag_counts
        Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").
        joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
    end  

    def tag_list
        tags.map(&:name).join(', ')
    end
    
    def tag_list=(names)
        self.tags = names.split(',').map do |n|
            Tag.where(name: n.strip).first_or_create!
        end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  USERS = { "admin" => "password" }

  before_action :authenticate, only: [:new, :edit, :destroy, :login]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = if params[:tag]
      Project.tagged_with(params[:tag])
    else
      Project.all
    end
  end

  def login
    @projects = if params[:tag]
      Project.tagged_with(params[:tag])
    else
      Project.all
    end
  end

  def contact
  end
  
  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html {  redirect_back(fallback_location: root_path) }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def current_user
    @current_user
  end

  helper_method :current_user

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end
    
    def authenticate
      current_user_name = nil
      is_authenticated = authenticate_or_request_with_http_digest do |username|
        current_user_name = username
        USERS[username]
      end
      @current_user = current_user_name if is_authenticated
      is_authenticated
   end
   

    

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:tag_list, :title, :thumb_img, :thumb_vid, :short_desc, :location, :period, :date, :long_desc, :recognition, :role, :views, collaborators_attributes: [:id, :name, :link, :contact, :project_id, :created_at, :updated_at, :_destroy], instructors_attributes: [:id, :name, :link, :contact, :project_id, :created_at, :updated_at, :_destroy], media_attributes: [:id, :caption, :link, :credits, :mediatype, :order, :aspect, :autoplay, :long_desc,  :project_id, :created_at, :updated_at, :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_collaborator_fields.html.erb
<fieldset class="col-6">
    <div class="media-card">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, id: :collaborator_name, :class => 'form-control' %>
    <%= f.label :link, "Link" %>
    <%= f.text_field :link , id: :collaborator_link, :class => 'form-control' %>
    <%= f.label :contact, "Contact" %>
    <%= f.text_field :contact , id: :collaborator_contact, :class => 'form-control' %>
    <%= f.hidden_field :_destroy %>
    <%= link_to("Remove", "#", class: "btn btn-danger remove_fields") %>
    </div>
</fieldset>

app/views/projects/_instructor_fields.html.erb
<fieldset class="col-6">
    <div class="media-card">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, id: :instructors_name, :class => 'form-control' %>
    <%= f.label :link, "Link" %>
    <%= f.text_field :link , id: :instructors_link, :class => 'form-control'%>
    <%= f.label :contact, "Contact" %>
    <%= f.text_field :contact , id: :instructors_contact, :class => 'form-control'%>
    <%= f.hidden_field :_destroy %>
    <%= link_to("Remove", "#", class: "btn btn-danger remove_fields") %>
    </div>
</fieldset>

app/views/projects/_tag_fields.html.erb
<fieldset>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", "#", class: "remove_fields" %>
</fieldset>

app/views/projects/contact.html.erb
<%# <script>loadPDF()</script> %>
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
<p id="unsupported-browser">
  You are awesome! Welcome to my portfolio! If you are seeing this message, it means that you are using a browser that might experience glitches. It would be awesome if you could view this site in Chrome or Firefox. If you cannot, it should still be okay. In case you find unbearable glitches, please provide feedback to hvvivek2007(at)gmail(dot)com.
</p>
<div class="wrapper" id="contact">

      <!-- Sidebar Start -->
      <nav id="sidebar">


        <div class="sidebar-content">
        

          <div class="sidebar-header">
            <p><%= link_to "Vivek HV", root_path %></p>
          </div>
          <a href="" class="tag_type">
          </a>
          <%= content_tag :div, class: "temp_information", data: {temp: Project.tag_counts.map{|x| [x.name, tag_path(x.name)]}} do %>
          <% end %>
          <hr>
          <ul class="sidebar-menu">
            <li><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/documents/Resume.pdf">Resum&#232</i></a></li>

          </ul>

        </div>
      </nav>

      <nav id="sidebar-mobile" class='col-12'>
        <div class="sidebar-content">
          <div class="sidebar-header">
            <p><%= link_to "Vivek HV", root_path %></p>
          
        </div>
        <div class="row align-items-center">
            
            <a  href="" class="col tag_type tag_type_mobile">
            </a>
          </div>
      </nav>
      <!-- Sidebar End -->

      <!-- Content Start -->
      <div class="content" id="style-3">

        <p id="key-info">You can use arrow keys to navigate</p>
        <img id="right-key" src ="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/right-key.png">
        <img id="left-key" src ="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/left-key.png">
        
        <div class="row1">
          <div class="resume-container text-center">
            <h4>About me</h4>
            <div class="self-container text-center">
            <img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/self/1.png" width=250 class="rounded" alt="..." onmouseover="hideThis(this)">
            <video class="vid-card"  width="250" height="250" muted loop autoplay onmouseout="hideVideo(this)">
                <source src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/self/7_1.mp4" type="video/mp4">
                Your browser does not support HTML5 video.
            </video>
            </div>
            <div class="contact-container">
            <a href='mailto:vivekhv@mde.harvard.edu'><i class="far fa-envelope"></i></a>
            <a href='https://www.facebook.com/ItsreallyVivek'><i class="fab fa-facebook-square"></i></a>
            <a href='https://www.linkedin.com/in/vivek-h-v'><i class="fab fa-linkedin"></i></a>
            <a href='https://github.com/hvvivek'><i class="fab fa-github"></i>  </a>

              <p>Hi! I am Vivek HV.</p> <p> Designer. Engineer. Artist. &nbsp Student.  </p>
              <p>Having lived in India all my life, I have observed and experienced the redoubtable change that technology brings to society. For good and bad.<p>
              <p>I am passionate about using technology to change lives for the better. I intend for my portfolio to document this pursuit.</p>
              <p>I am currently part of the second cohort of the Masters in Design Engineering program at Harvard University. Feel free to reach out to me!</p>
              
            </div>
          </div>
        
          

          <div class="resume-container">
            <h4>Older Projects</h4>
            <div class="project-container">
              <div class="square"><a href="http://vivek-hv.squarespace.com/#/web-development/"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/old_projects/Web.png" ></a></div>
              <div class="square"><a href="http://vivek-hv.squarespace.com/#/project-viento/"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/old_projects/Viento.jpg" ></a></div>
              <div class="square"><a href="http://vivek-hv.squarespace.com/#/machine-learning-big-data/"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/old_projects/MLDS.png" ></a></div>
              <div class="square"><a href="http://vivek-hv.squarespace.com/#/android-development/"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/old_projects/Android.png" ></a></div>
              <div class="square"><a href="http://vivek-hv.squarespace.com/#/project-cube/"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/old_projects/Cube.png" ></a></div>
            </div>
          </div>

          <div class="resume-container">
            <h4>Art</h4>
            <div class="art-container">
              <div class="square"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/art1.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/squares/1.png" ></a></div>
              <div class="square"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/art7.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/squares/2.png" ></a></div>
              <div class="square"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/art6.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/squares/3.png" ></a></div>
              <div class="square"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/art5.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/squares/4.png" ></a></div>
              <div class="square"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/art4.png"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/squares/5.png" ></a></div>
              <div class="square"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/art3.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/artwork/squares/6.png" ></a></div>

            </div>
          </div>

          <div class="resume-container">
            <h4>Photography</h4>
            <div class="photograph-container">
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/9.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/1.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/8.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/2.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/7.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/3.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/6.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/4.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/5.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/5.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/4.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/6.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/3.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/7.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/2.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/8.png" ></a></div>
              <div class="square-photo"><a href="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/full/1.jpg"><img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/photographs/squares/9.png" ></a></div>

            </div>
          </div>
        </div>
      </div>
      <!-- Content End -->

    </div>

app/views/projects/edit.html.erb
<div class="container-fluid">
<div class="col-10 offset-1">
<h1 class="center">Editing Project</h1>

<%= render 'form', project: @project %>

<div class="container cancel-links">

<%= link_to('Show', @project) %> | 
<%= link_to('Back', projects_path) %>
</div>
</div>
<%= tinymce %>
</div>

app/views/projects/index.html.erb
<p id="unsupported-browser">
        You are awesome! Welcome to my portfolio! If you are seeing this message, it means that you are using a browser that might experience glitches. It would be awesome if you could view this site in Chrome or Firefox. If you cannot, it should still be okay. In case you find unbearable glitches, please provide feedback to hvvivek2007(at)gmail(dot)com.
      </p>
<div class="wrapper">
      
      <!-- Sidebar Start -->
      <nav id="sidebar">


        <div class="sidebar-content">
        

          <div class="sidebar-header">
            <p><%= link_to "Vivek HV", root_path %></p>
          </div>

          <a href="" class="tag_type">
          </a>
          <%= content_tag :div, class: "temp_information", data: {temp: Project.tag_counts.map{|x| [x.name, tag_path(x.name)]}} do %>
          <% end %>
          
          <hr>
          <ul class="sidebar-menu">
            <li><%= link_to "About", controller: "projects", action: "contact" %></li>
          </ul>

        </div>

        <div id="arrows">
          <img src = "https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/left.png" id="arrow-left">
          <img src = "https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/right.png" id="arrow-right">
        </div>
      </nav>

      <nav id="sidebar-mobile" class='col-12'>
        <div class="sidebar-content">
          <div class="sidebar-header">
            <p><%= link_to "Vivek HV", root_path %></p>
          </div>

          
          <div class="row align-items-center">
            
            <a  href="" class="col tag_type tag_type_mobile">
            </a>
            <div class="cursor">
            </div>
          </div>

          <ul class="sidebar-menu">
            <li><%= link_to "About", controller: "projects", action: "contact" %></li>
          </ul>
        </div>
      </nav>
      <!-- Sidebar End -->

      <!-- Content Start -->
      <div class="content" id="style-3">
        <p id="key-info">You can use arrow keys to navigate</p>
        <img id="right-key" src ="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/right-key.png">
        <img id="left-key" src ="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/left-key.png">
        <div class="row1">

    <% @projects.each_with_index do |project, index| %>
    
    <%= link_to(project) do %>
          <div class="card">
            <p class="side-text"><%= project.period %></p>
            <div class="wrapper-rhs" target='vid-<%= index %>' toggle="img-<%= index %>">
              <div class="img-container">
                <img class="img-card" src="<%= project.thumb_img %>" target='vid-<%= index %>' toggle="img-<%= index %>">
                <video class="vid-card" width="400" height="400" target='img-<%= index %>' toggle="vid-<%= index %>" playsinline muted loop>
                    <source src="<%= project.thumb_vid %>" type="video/mp4">
                    <img class="img-card" src="<%= project.thumb_img %>">
                    Your browser does not support HTML5 video.
                </video>
              </div>

              <div class="text-wrapper">
                <p class="title"><%= link_to project.title, project %></p>
                <p class="project-tags">
                    <% project.tags.each_with_index do |tag, index| %>
                      <%= link_to '#' + tag.name, tag_path(tag.name) %>
                    <% end %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
<!--
        <td><%#= link_to 'Edit', edit_project_path(project) %></td>
        <td><%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>
    
        </div>
      </div>
      <!-- Content End -->

    </div>

app/views/projects/login.html.erb
<div class="wrapper">
      <!-- Sidebar Start -->
      <nav id="sidebar">


        <div class="sidebar-content">
        

          <div class="sidebar-header">
            <p>Vivek HV</p>
          </div>
          <div id="tag_cloud">
            <% tag_cloud Project.tag_counts, %w[s m l] do |tag, css_class| %>
              <%#= link_to tag.name, tag_path(tag.name), class: css_class %>
              <%= link_to "#" + tag.name, tag_path(tag.name), class: "tags" %>
            <% end %>
          </div>
          <ul class="sidebar-menu">
            <li><%= link_to "Contact", controller: "projects", action: "contact" %></li>
          </ul>


        </div>
      </nav>

      <nav id="sidebar-mobile" class='col-12'>
        <div class="sidebar-content">
          <div class="sidebar-header">
            <p>Vivek HV</p>

            <div id="tag_cloud">
              <% tag_cloud Project.tag_counts, %w[s m l] do |tag, css_class| %>
                <%# <%= link_to tag.name, tag_path(tag.name), class: css_class %> %>
                <%= link_to tag.name, tag_path(tag.name) %>
              <% end %>
            </div>
          </div>


          
          <ul class="sidebar-menu">
            <li><a href="#">Contact</a></li>
          </ul>



        </div>
      </nav>
      <!-- Sidebar End -->

      <!-- Content Start -->
      <div class="content" id="style-3">
        <div class="row1">

    <% @projects.each_with_index do |project, index| %>

          <div class="card">
            <!-- <p class="side-text">Graduate School of Design / Harvard University / Fall 2017</p> -->
            <div class="wrapper-rhs">
              <div class="img-container">
                <img class="img-card" src="<%= project.thumb_img %>" target='vid-<%= index %>' toggle="img-<%= index %>">
                <video class="vid-card"  width="400" height="400" target='img-<%= index %>' toggle="vid-<%= index %>"   muted loop>
                    <source src="<%= project.thumb_vid %>" type="video/mp4">
                    Your browser does not support HTML5 video.
                </video>
              </div>

              <div class="text-wrapper">
                <p class="title"><%= link_to project.title, project %></p>
                <div class="icons row">
                    <div class="plus col">
                        <%= link_to image_tag("https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/plus.jpg",width:"50"), new_project_path %>
                    </div>
                    <div class="plus col">
                        <%= link_to image_tag("https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/delete.jpg",width:"50"), project, method: :delete, data: { confirm: 'Are you sure?' }  %>
                    </div>
                    <div class="plus col">
                        <%= link_to image_tag("https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/edit.jpg",width:"50"), edit_project_path(project) %>
                    </div>
                </div>
                <!-- <p class="sub-text-1">#productdesign #spatialdesign #vr #creativity #productdesign #spatialdesign #vr</p> -->
              </div>
            </div>
          </div>
<!--
        <td><%#= link_to 'Edit', edit_project_path(project) %></td>
        <td><%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>








        </div>
      </div>
      <!-- Content End -->

    </div>

app/views/projects/new.html.erb
<h1>New Project: <%= @current_user %></h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="unsupported-browser">
  You are awesome! Welcome to my portfolio! If you are seeing this message, it means that you are using a browser that might experience glitches. It would be awesome if you could view this site in Chrome or Firefox. If you cannot, it should still be okay. In case you find unbearable glitches, please provide feedback to hvvivek2007(at)gmail(dot)com.
</p>      
<div id="project" class="wrapper">

      <!-- Sidebar Start -->
      <nav id="sidebar">
        <div class="sidebar-content">
          <a href=<%= projects_path %>>
          <div class="back-arrow">
              <img src="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/back.jpg" width="75" >
          </div>
          </a>
          <div class="sidebar-header">
            <p><%= link_to "Vivek HV", root_path %></p>
          </div>
          <a href="" class="tag_type">
          </a>
          <%= content_tag :div, class: "temp_information", data: {temp: Project.tag_counts.map{|x| [x.name, tag_path(x.name)]}} do %>
          <% end %>
          <hr>

          <ul class="sidebar-menu">
            <li><%= link_to "About", controller: "projects", action: "contact" %></li>
          </ul>
        </div>
      </nav>

      <nav id="sidebar-mobile" class='col-12'>
        <div class="sidebar-content">
          <div class="sidebar-header">
            <p><%= link_to "Vivek HV", root_path %></p>
          </div>
          <div class="row align-items-center">
            
            <a  href="" class="col tag_type tag_type_mobile">
            </a>
            <div class="cursor">
            </div>
          </div>
          <ul class="sidebar-menu">
            <li><%= link_to "About", controller: "projects", action: "contact" %></li>
          </ul>
        </div>
      </nav>
      <!-- Sidebar End -->

      <!-- Content Start -->
      <div class="content" id="style-3">
        <p id="key-info">You can use arrow keys to navigate</p>
        <img id="right-key" src ="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/right-key.png">
        <img id="left-key" src ="https://s3.us-east-2.amazonaws.com/portfolio-vivek/images/icons/left-key.png">
        
        <div class="row1">

            <div class="card">
                <!-- <p class="side-text">01 Atelier</p> -->
                <div class="wrapper-rhs">
                  <div class="img-container">
                    <img class="img-card" src='<%= @project.thumb_img %>' target='vid-1' toggle="img-1">
                    <video class="vid-card"  width="400" height="400" target='img-1' toggle="vid-1"  loop>
                        <source src="<%= @project.thumb_vid %>" type="video/mp4" autoplay>
                        Your browser does not support HTML5 video.
                    </video>
                  </div>
    
                  <div class="text-wrapper">
                    <p class="sub-text-1"><%= @project.period %> <br> <%= @project.location %></p>

                    
                    <% if (!@project.instructors.nil? & @project.instructors.any?) %>
                      <p class="sub-text-1">Instructor(s)/Professor(s):<br> 
                      <% @project.instructors.each_with_index do |instructor, index| %>
                        <% if index > 0 %>
                        , 
                        <% end %>
                        <a href="<%= instructor.link %>"><%= instructor.name %></a>
                      <% end %>
                      </p>
                    <% end %>

                    <% if (!@project.collaborators.nil? & @project.collaborators.any?) %>
                      <p class="sub-text-1">Collaborator(s):<br> 
                      <% @project.collaborators.each_with_index do |collaborator, index| %>
                        <% if index > 0 %>
                        , 
                        <% end %>
                        <a href="<%= collaborator.link %>"><%= collaborator.name %></a>
                      <% end %>
                      </p>
                    <% end %>    
                  </div>
                </div>
              </div>

              <div class="card2">
                <!-- <p class="side-text">01 Atelier</p> -->
                <div class="wrapper-rhs">
                  <div class="text-wrapper">
                    <h3 class="title"><%= @project.title %></h3>
                    <p class="short-desc"><%= @project.short_desc %></p>
                    <div class="long-desc"><%= @project.long_desc.html_safe %></div>
                </div>
                </div>
              </div>

              <% if !@project.media.nil? %>
                <% count = 0 %>
                <% @project.media.order(:order).each_with_index do |medium, index| %>
                  <% if medium.mediatype == 'Text'%>
                    <div class="card2">
                        <!-- <p class="side-text">01 Atelier</p> -->
                        <div class="wrapper-rhs">
                          <div class="text-wrapper">
                            <div class="long-desc media-long-desc"><%= medium.long_desc.html_safe %></div>
                        </div>
                        </div>
                      </div>
                  <%else%>
                    <% if medium.aspect == 0 %>
                          <div class="card4 align-items-center">
                          <% if medium.mediatype == 'Image' %>
                            <img class="img-card-extra" src="<%= medium.link %>" >
                          <% end %>
                          <% if medium.mediatype == 'Video' %>
                            <video width="540" muted <% if(medium.autoplay > 0 ) %> autoplay loop <% end %> >
                                <source src="<%= medium.link %>" type="video/mp4" >
                                Your browser does not support HTML5 video.
                            </video>
                          <% end %>
                          <% count += 1 %>
                          </div>
                    <% end %>

                    <% if medium.aspect == 1 %>
                      <div class="card3">
                        <% if medium.mediatype == 'Image' %>
                          <img class="img-card-extra2" src="<%= medium.link %>" >
                        <% end %>
                        <% if medium.mediatype == 'Video' %>
                          <video width="570" muted <% if(medium.autoplay > 0 ) %> autoplay loop <% end %> >
                              <source src="<%= medium.link %>" type="video/mp4" >
                              Your browser does not support HTML5 video.
                          </video>
                        <% end %>
                      </div>
                    <% end %>

                  <% end %>
                <% end %>
              <%end%>  
        </div>
      </div>
      <!-- Content End -->