config/routes.rb
Rails.application.routes.draw do
  resources :taggings
  # resources :tags
  resources :media
  resources :collaborators
  resources :instructors
  resources :projects

  root 'projects#index'
  get 'tags/:tag', to: 'projects#index', as: :tag
  get 'login', to: 'projects#login'
  get 'contact', to: 'projects#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  before_action :set_tagging, only: [:show, :edit, :update, :destroy]

  # GET /taggings
  # GET /taggings.json
  def index
    @taggings = Tagging.all
  end

  # GET /taggings/1
  # GET /taggings/1.json
  def show
  end

  # GET /taggings/new
  def new
    @tagging = Tagging.new
  end

  # GET /taggings/1/edit
  def edit
  end

  # POST /taggings
  # POST /taggings.json
  def create
    @tagging = Tagging.new(tagging_params)

    respond_to do |format|
      if @tagging.save
        format.html { redirect_to @tagging, notice: 'Tagging was successfully created.' }
        format.json { render :show, status: :created, location: @tagging }
      else
        format.html { render :new }
        format.json { render json: @tagging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taggings/1
  # PATCH/PUT /taggings/1.json
  def update
    respond_to do |format|
      if @tagging.update(tagging_params)
        format.html { redirect_to @tagging, notice: 'Tagging was successfully updated.' }
        format.json { render :show, status: :ok, location: @tagging }
      else
        format.html { render :edit }
        format.json { render json: @tagging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taggings/1
  # DELETE /taggings/1.json
  def destroy
    @tagging.destroy
    respond_to do |format|
      format.html { redirect_to taggings_url, notice: 'Tagging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tagging
      @tagging = Tagging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tagging_params
      params.require(:tagging).permit(:tag_id, :project_id)
    end
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/taggings/_form.html.erb
<%= form_with(model: tagging, local: true) do |form| %>
  <% if tagging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tagging.errors.count, "error") %> prohibited this tagging from being saved:</h2>

      <ul>
      <% tagging.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.text_field :tag_id, id: :tagging_tag_id %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :tagging_project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/taggings/edit.html.erb
<h1>Editing Tagging</h1>

<%= render 'form', tagging: @tagging %>

<%= link_to 'Show', @tagging %> |
<%= link_to 'Back', taggings_path %>

app/views/taggings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taggings</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taggings.each do |tagging| %>
      <tr>
        <td><%= tagging.tag %></td>
        <td><%= tagging.project %></td>
        <td><%= link_to 'Show', tagging %></td>
        <td><%= link_to 'Edit', edit_tagging_path(tagging) %></td>
        <td><%= link_to 'Destroy', tagging, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tagging', new_tagging_path %>

app/views/taggings/new.html.erb
<h1>New Tagging</h1>

<%= render 'form', tagging: @tagging %>

<%= link_to 'Back', taggings_path %>

app/views/taggings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tagging.tag %>
</p>

<p>
  <strong>Project:</strong>
  <%= @tagging.project %>
</p>

<%= link_to 'Edit', edit_tagging_path(@tagging) %> |
<%= link_to 'Back', taggings_path %>